#ifndef BASE_H_
#define BASE_H_
#include <cstdint>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <sstream>
#include <string>
#include <cstring>
#include <float.h>
#include <math.h>
#include <limits>
#include <numeric>
#include <chrono>
#include <random>
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <bitset>
#endif
