//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.FromFile(&quot;C:\Users\Aravind\Documents\Visual Studio 2013\Projects\WindowsFormsApplication1\bin\Debug\File001.bmp&quot;).
        /// </summary>
        internal static string File001 {
            get {
                return ResourceManager.GetString("File001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.FromFile(&quot;C:\Users\Aravind\Documents\Visual Studio 2013\Projects\WindowsFormsApplication1\bin\Debug\File002.bmp&quot;).
        /// </summary>
        internal static string File002 {
            get {
                return ResourceManager.GetString("File002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.FromFile(&quot;C:\Users\Aravind\Documents\Visual Studio 2013\Projects\WindowsFormsApplication1\bin\Debug\File003.bmp&quot;).
        /// </summary>
        internal static string File003 {
            get {
                return ResourceManager.GetString("File003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.FromFile(&quot;C:\Users\Aravind\Documents\Visual Studio 2013\Projects\WindowsFormsApplication1\bin\Debug\File004.bmp&quot;).
        /// </summary>
        internal static string File004 {
            get {
                return ResourceManager.GetString("File004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.FromFile(&quot;C:\Users\Aravind\Documents\Visual Studio 2013\Projects\WindowsFormsApplication1\bin\Debug\File005.bmp&quot;).
        /// </summary>
        internal static string File005 {
            get {
                return ResourceManager.GetString("File005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.FromFile(&quot;C:\Users\Aravind\Documents\Visual Studio 2013\Projects\WindowsFormsApplication1\bin\Debug\File006.bmp&quot;).
        /// </summary>
        internal static string File006 {
            get {
                return ResourceManager.GetString("File006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.FromFile(&quot;C:\Users\Aravind\Documents\Visual Studio 2013\Projects\WindowsFormsApplication1\bin\Debug\File007.bmp&quot;).
        /// </summary>
        internal static string File007 {
            get {
                return ResourceManager.GetString("File007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.FromFile(&quot;C:\Users\Aravind\Documents\Visual Studio 2013\Projects\WindowsFormsApplication1\bin\Debug\File008.bmp&quot;).
        /// </summary>
        internal static string File008 {
            get {
                return ResourceManager.GetString("File008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.FromFile(&quot;C:\Users\Aravind\Documents\Visual Studio 2013\Projects\WindowsFormsApplication1\bin\Debug\File008.bmp&quot;).
        /// </summary>
        internal static string File009 {
            get {
                return ResourceManager.GetString("File009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.FromFile(&quot;C:\Users\Aravind\Documents\Visual Studio 2013\Projects\WindowsFormsApplication1\bin\Debug\File009.bmp&quot;).
        /// </summary>
        internal static string File010 {
            get {
                return ResourceManager.GetString("File010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.FromFile(&quot;C:\Users\Aravind\Documents\Visual Studio 2013\Projects\WindowsFormsApplication1\bin\Debug\File010.bmp&quot;).
        /// </summary>
        internal static string File011 {
            get {
                return ResourceManager.GetString("File011", resourceCulture);
            }
        }
    }
}
